

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: sineos-open-webui

    env_file:
      - .env

    restart: unless-stopped

    network_mode: pasta

    ports:
      - "127.0.0.1:3000:8080"

    environment:
      OLLAMA_BASE_URL: http://host.containers.internal:11434

    volumes:
      - ../../volumes/open-webui/data:/app/backend/data
